config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)  


  devise_for :users,
             :path => '', :path_names => {:sign_in => 'sign-in', :sign_out => 'sign-out', :sign_up => 'sign-up',
             :edit_profile => 'profile'},
              :controllers => {:omniauth_callbacks => 'omniauth_callbacks', :registrations => 'registrations'}

  resources :users, only: [:show]
  resources :doctors, only: [:show]
  resources :patients, only: [:show]
  resources :rooms
  resources :photos

  resources :rooms do
    resources :reservations, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :rooms do
    resources :reviews, only: [:create, :destroy]
  end

  resources :rooms do
    resources :purchases, only: [:create]
  end
  resources :invites
  
  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  get '/your-trips' => 'reservations#your_trips'
  get '/your-reservations' => 'reservations#your_reservations'

  get '/your-sales' => 'purchases#your_sales'
  get '/your-purchases' => 'purchases#your_purchases'

  post '/notify' => 'reservations#notify'
  post '/your-trips' => 'reservations#your_trips'

  post '/purchase_notify' => 'purchases#notify'
  #post '/your-sales' => 'purchases#your_sales'

  get '/search' => 'pages#search'
  get '/dashboard' => 'pages#dashboard'
  

  resources :activities, only: [:index]
  resources :room_steps, only: [:show, :create, :update, :index]
  
  get '/family-members' => 'users#family_members'

  get 'users/:id/friends' => 'users#friends' , as: :friends
  get 'patient/:id/relatives' => 'patients#relatives'
  get 'patient/:id/bookings' => 'patients#bookings'
  
  get 'doctor/:id/leads' => 'doctors#leads', as: :leads 
  
  delete 'relative/:id' => "users#remove_relative"
  delete 'friend/:id' => "users#remove_friend"
  delete 'booking/:id' => "users#remove_booking"

  resources :bookings, only: [:create,:index, :update]
  get '/rooms/:room_id/booking' => "bookings#step_first"
  get '/sample' => "pages#sample"
  get '/test' => "pages#test"
  resources :booking_steps
  resources :categories, only: [:show]

  get '/mark_as_read' => "activities#mark_as_read"
   
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  #before_action :authenticate_user!, except: [:notify]
  protect_from_forgery except: [:notify, :your_sales]
  skip_before_action :authenticate_patient!, :authenticate_doctor!

  def create
    @purchase = current_user.purchases.create(purchase_params)
    room  = @purchase.room

    if @purchase
      values = {
        business: 'ariefrizkyr-facilitator@gmail.com',
        cmd: '_xclick-subscriptions',
        upload: 1,
        notify_url: 'http://98a4b73e.ngrok.io/purchase_notify',
        item_name: room.name,
        invoice: @purchase.id,
        quantity: 1,
        return: 'http://98a4b73e.ngrok.io/',
        a3: @purchase.price,
        p3: 12,
        t3: 'M'

      }
      redirect_to "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
    else
      redirect_to room, alert: "Something went wrong!"
    end
  end

  def notify
    params.permit!
    purchase = Purchase.find(params[:item_number])

    if params[:payment_status].eql? "Completed"
      purchase.update_attributes notification_params: params, status: true, transaction_id: params[:txn_id], purchased_at: Time.now
    else
      purchase.destroy
    end
    render nothing: true

  end

 
  def your_sales
    @sales = current_user.purchases.where("status = ?", true)
  end

  def your_purchases
    @rooms = current_user.rooms
  end

  private
    def purchase_params
      params.require(:purchase).permit(:price, :name, :room_id)
    end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/_form_enterprise.html.haml
= form_for([@room, @room.purchases.new]) do |f|
  = f.hidden_field :room_id, value: @room.id
  = f.hidden_field :name, value: 'enterprise'
  = f.hidden_field :price, value: '499'
  %h4
    %span#message
  = f.submit "UPGRADE $499/month", class: "btn btn-primary btn-block"

app/views/purchases/_form_featured.html.haml
= form_for([@room, @room.purchases.new]) do |f|
  = f.hidden_field :room_id, value: @room.id
  %h4
    %span#message
  = check_box_tag "purchase[price]", '199'
  = label_tag "Featured"
  = f.submit "UPGRADE", class: "btn btn-primary wide"

app/views/purchases/your_purchases.html.haml
.row
  = render '/shared/sidebarnav'
  .col-md-9
    .panel.panel-default
      .panel-heading
        Your purchases
      .panel-body
        - @rooms.each do |room|
          - room.purchases.each do |purchase|
            - if purchase.status
              .row
                .col-md-6
                  = link_to room_path(purchase.room) do
                    = image_tag purchase.room.photos[0].image.url(:thumb)
                .col-md-2
                  = link_to user_path(purchase.user) do
                    = image_tag avatar_url(purchase.user), class: 'img-circle avatar-medium'
                .col-md-2.right
                  %h4
                    $#{purchase.price}
              %hr/

app/views/purchases/your_sales.html.haml
.row
  =# render '/shared/sidebarnav'
  .col-md-9
    .panel.panel-default
      .panel-heading
        Your sales
      .panel-body
        - @sales.each do |sale|
          .row
            .col-md-6
              = link_to room_path(sale.room) do
                = image_tag sale.room.photos[0].image.url(:thumb)
            .col-md-2
              = link_to user_path(sale.room.user) do
                = image_tag avatar_url(sale.room.user), class: 'img-circle avatar-medium'
            .col-md-2.right
              %h4
                $#{sale.price}
          %hr/