config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)  


  devise_for :users,
             :path => '', :path_names => {:sign_in => 'sign-in', :sign_out => 'sign-out', :sign_up => 'sign-up',
             :edit_profile => 'profile'},
              :controllers => {:omniauth_callbacks => 'omniauth_callbacks', :registrations => 'registrations'}

  resources :users, only: [:show]
  resources :doctors, only: [:show]
  resources :patients, only: [:show]
  resources :rooms
  resources :photos

  resources :rooms do
    resources :reservations, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :rooms do
    resources :reviews, only: [:create, :destroy]
  end

  resources :rooms do
    resources :purchases, only: [:create]
  end
  resources :invites
  
  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  get '/your-trips' => 'reservations#your_trips'
  get '/your-reservations' => 'reservations#your_reservations'

  get '/your-sales' => 'purchases#your_sales'
  get '/your-purchases' => 'purchases#your_purchases'

  post '/notify' => 'reservations#notify'
  post '/your-trips' => 'reservations#your_trips'

  post '/purchase_notify' => 'purchases#notify'
  #post '/your-sales' => 'purchases#your_sales'

  get '/search' => 'pages#search'
  get '/dashboard' => 'pages#dashboard'
  

  resources :activities, only: [:index]
  resources :room_steps, only: [:show, :create, :update, :index]
  
  get '/family-members' => 'users#family_members'

  get 'users/:id/friends' => 'users#friends' , as: :friends
  get 'patient/:id/relatives' => 'patients#relatives'
  get 'patient/:id/bookings' => 'patients#bookings'
  
  get 'doctor/:id/leads' => 'doctors#leads', as: :leads 
  
  delete 'relative/:id' => "users#remove_relative"
  delete 'friend/:id' => "users#remove_friend"
  delete 'booking/:id' => "users#remove_booking"

  resources :bookings, only: [:create,:index, :update]
  get '/rooms/:room_id/booking' => "bookings#step_first"
  get '/sample' => "pages#sample"
  get '/test' => "pages#test"
  resources :booking_steps
  resources :categories, only: [:show]

  get '/mark_as_read' => "activities#mark_as_read"
   
end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |msg| %>
      toastr.error('<%= msg %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_devisemes.html.haml
- unless resource.errors.empty?
  :javascript
    <haml_silent>     resource.errors.full_messages.each do |msg| 
    </haml_silent><haml_block>      toastr.error('#{msg}')
    </haml_block>

app/views/shared/_footer.html.haml
%section.page-footer.p-b-0.ng-scope
  .container
    .footer-sitemap
      .row.ng-isolate-scope.accordion-footer{"ui-accordion" => "", "ui-accordion-footer" => ""}
        .col-md-10.col-md-offset-1
          .col-md-4.col-sm-4
            .footer-left
              %img{:src => "/assets/home/footer-logo.png"}/
              %ul.social-list
                %li
                  %a{:href => "javascript:void(0)"}
                    %i.fa.fa-twitter
                %li
                  %a{:href => "javascript:void(0)"}
                    %i.fa.fa-facebook
                %li
                  %a{:href => "javascript:void(0)"}
                    %i.fa.fa-pinterest-p
                %li
                  %a{:href => "javascript:void(0)"}
                    %i.fa.fa-google-plus
                %li
                  %a{:href => "javascript:void(0)"}
                    %i.fa.fa-instagram
              .thumbtack-box
                %a{:href => "javascript:void(0)"}
                  %img{:src => "/assets/home/thumbtack-icon.png"}/
                  .thumbtack-textContainer
                    %span GoDoc Guarantee
                    %span $1M Treatment Protection
          .col-md-8.col-sm-8.clearbox
            .col-sm-3
              .item.ng-scope{"ui-accordion-item" => ""}
                %h4.text-uppercase.m-b-40.title
                  %a{"ng-click" => "toggle()", "ng-href" => "", "ng-transclude" => "", "ui-accordion-item-toggle" => ""}
                    %span.ng-scope Company
                %ul.list-unstyled.text-short{:style => ""}
                  %li
                    %a{:href => "javascript:void(0)"} About
                  %li
                    %a{:href => "javascript:void(0)"} Jobs
                  %li
                    %a{:href => "javascript:void(0)"} Team
                  %li
                    %a{:href => "javascript:void(0)"} Blogs
            .col-sm-3
              .item.ng-scope{"ui-accordion-item" => ""}
                %h4.text-uppercase.m-b-40.title
                  %a{"ng-click" => "toggle()", "ng-href" => "", "ng-transclude" => "", "ui-accordion-item-toggle" => ""}
                    %span.ng-scope Customers
                %ul.list-unstyled.m-b-40.text-short{:style => ""}
                  %li
                    %a{:href => "javascript:void(0)"} How it works
                  %li
                    %a{:href => "javascript:void(0)"} Safety
                  %li
                    %a{:href => "javascript:void(0)"} iPhone app
                  %li
                    %a{:href => "javascript:void(0)"} Services Near Me
                  %li
                    %a{:href => "javascript:void(0)"} Cost Estimates
                  %li
                    %a{:href => "javascript:void(0)"} Service Guides
            .col-sm-3.ng-scope{"ui-accordion-item" => ""}
              .item.ng-scope{"ui-accordion-item" => ""}
                %h4.text-uppercase.m-b-40.title
                  %a{"ng-click" => "toggle()", "ng-href" => "", "ng-transclude" => "", "ui-accordion-item-toggle" => ""}
                    %span.ng-scope Pros
                %ul.list-unstyled.text-short{:style => ""}
                  %li
                    %a{:href => "javascript:void(0)"} How it works
                  %li
                    %a{:href => "javascript:void(0)"} Sign up
                  %li
                    %a{:href =>"javascript:void(0)"} Pro center
                  %li
                    %a{:href => "javascript:void(0)"} Success stories
                  %li
                    %a{:href => "javascript:void(0)"} Mobile app
            .col-sm-3.ng-scope{"ui-accordion-item" => ""}
              .item.ng-scope{"ui-accordion-item" => ""}
                %h4.text-uppercase.m-b-40.title
                  %a{"ng-click" => "toggle()", "ng-href" => "", "ng-transclude" => "", "ui-accordion-item-toggle" => ""}
                    %span.ng-scope Support
                %ul.list-unstyled.text-short{:style => ""}
                  %li
                    %a{:href => "javascript:void(0)"} Help center
    .page-bottom
      .col-md-10.col-md-offset-1
        .col-md-6.col-sm-6.clearbox
          %p © 2017 Thumbtack, Inc.
        .col-md-6.col-sm-6.clearbox
          %ul.footer-links
            %li
              %a{:href => "javascript:void(0)"} Privacy Policy
            %li
              %a{:href => "javascript:void(0)"} Terms of use

app/views/shared/_header.html.haml
.header-fixed
  %nav.navbar.navbar-default
    .container-fluid
      .navbar-header
        %button.navbar-toggle{"aria-controls" => "navbar", "aria-expanded" => "true", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "/"}
          %img{:src => "/assets/home/gotdoc-logo.png"} 

      #navbar.navbar-collapse.collapse.in{"aria-expanded" => "true"}
        %ul.nav.navbar-nav
          %li.header-navbar
            .search.visible-md.visible-lg.ng-scope{"data-ng-controller" => "uiSearchController"}
              = form_tag search_path, method: :get do
                .input-group
                  %span.button{"ng-click" => "toggleDropDown()"}
                  = text_field_tag :location, params[:location], placeholder: 'City, Zip Code or State' 
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Browse
              %span.caret
            %ul.dropdown-menu
              %li
                %a{:href => "javascript:void(0)"} Categories
              %li
                %a{:href => "javascript:void(0)"} Procedures
              %li
                %a{:href => "javascript:void(0)"} Symptoms
              %li
                %a{:href => "javascript:void(0)"} Locations
        %ul.nav.navbar-nav.navbar-right
          - unless user_signed_in?
            %li
              %a{:href => "/room_steps"}
                List your practice 

            %li
              %a{:href => "/sign-up"}
                %span.glyphicon.glyphicon-user
                Sign Up
            %li
              %a{:href => "/sign-in"}
                %span.glyphicon.glyphicon-log-in
                Login

          - else

            %li= link_to icon('envelope'), conversations_path

            %li= link_to icon('question'), "javascript:void(0)"

            %li.nav-icon-btn.nav-icon-btn-danger.dropdown#notifications
              = render "shared/notifications"

            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                = image_tag avatar_url(current_user), class: 'img-circle avatar-small'
                = current_user.fullname
                %span.caret
              %ul.dropdown-menu
                - if current_user.type == "Doctor"
                  %li= link_to 'Dashboard', dashboard_path
                  %li= link_to 'My profile', user_path(current_user.id)
                  %li= link_to 'Rooms', rooms_path
                - else
                  %li= link_to 'My profile', user_path(current_user.id)
                  %li= link_to 'Appointments', "/patient/#{current_patient.id}/bookings"
                %li= link_to 'Settings', edit_user_registration_path(personal:true)
                %li= link_to 'Sign out', destroy_user_session_path, method: :delete
    / /.nav-collapse
  / /.container-fluid


- content_for :javascript do
  :javascript

    $('li#notifications').click(function(){
      $.ajax({
        url: '/mark_as_read',
        type: "GET",
        success: function(data) {
        },
        failure: function() {
        }
      }); 

    })

app/views/shared/_hubspot.html.erb
  <script type="text/javascript" id="hs-script-loader" async defer src="//js.hs-scripts.com/3312243.js"></script>

app/views/shared/_message.html.erb
<% if @errors && @errors.present? %>
  <script type="text/javascript">
    <% @errors.full_messages.each do |msg| %>
      toastr.error('<%= msg %>')
    <% end %>
  </script>
<% end %>

<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_notifications.html.haml
%a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}

  - count = unread_notification.count
  - if count > 0
    %span.label= count
  %i.nav-icon.fa.fa-bell
  %span.small-screen-text Notifications


.dropdown-menu.widget-notifications.no-padding{:style => "width: 300px"}
  - if count > 0
    .notifications-list
      - unread_notification.first(5).each do |activity|
        .notification
          .notification-description
            = render_activity activity
          .notification-ago= time_ago_in_words(activity.created_at)
    = link_to 'See all', activities_path, class: 'notifications-link'  if count > 5
  - else
    .see-all-link.text-center 
      You don't have any new notifications yet.
  