config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)  


  devise_for :users,
             :path => '', :path_names => {:sign_in => 'sign-in', :sign_out => 'sign-out', :sign_up => 'sign-up',
             :edit_profile => 'profile'},
              :controllers => {:omniauth_callbacks => 'omniauth_callbacks', :registrations => 'registrations'}

  resources :users, only: [:show]
  resources :doctors, only: [:show]
  resources :patients, only: [:show]
  resources :rooms
  resources :photos

  resources :rooms do
    resources :reservations, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :rooms do
    resources :reviews, only: [:create, :destroy]
  end

  resources :rooms do
    resources :purchases, only: [:create]
  end
  resources :invites
  
  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  get '/your-trips' => 'reservations#your_trips'
  get '/your-reservations' => 'reservations#your_reservations'

  get '/your-sales' => 'purchases#your_sales'
  get '/your-purchases' => 'purchases#your_purchases'

  post '/notify' => 'reservations#notify'
  post '/your-trips' => 'reservations#your_trips'

  post '/purchase_notify' => 'purchases#notify'
  #post '/your-sales' => 'purchases#your_sales'

  get '/search' => 'pages#search'
  get '/dashboard' => 'pages#dashboard'
  

  resources :activities, only: [:index]
  resources :room_steps, only: [:show, :create, :update, :index]
  
  get '/family-members' => 'users#family_members'

  get 'users/:id/friends' => 'users#friends' , as: :friends
  get 'patient/:id/relatives' => 'patients#relatives'
  get 'patient/:id/bookings' => 'patients#bookings'
  
  get 'doctor/:id/leads' => 'doctors#leads', as: :leads 
  
  delete 'relative/:id' => "users#remove_relative"
  delete 'friend/:id' => "users#remove_friend"
  delete 'booking/:id' => "users#remove_booking"

  resources :bookings, only: [:create,:index, :update]
  get '/rooms/:room_id/booking' => "bookings#step_first"
  get '/sample' => "pages#sample"
  get '/test' => "pages#test"
  resources :booking_steps
  resources :categories, only: [:show]

  get '/mark_as_read' => "activities#mark_as_read"
   
end

app/controllers/booking_steps_controller.rb
class BookingStepsController < ApplicationController
	include Wicked::Wizard
	steps :first, :second

  skip_before_action :authenticate_doctor!
  
  def show
    case step
    when :first  
      @booking = current_patient.bookings.create(room_id: params[:room_id])
    when :second
      @booking = Booking.find(params[:booking_id])
      @booking.update_attribute(:friend_id, params[:friend_id]) if params[:friend_id].present?  
    end
    render_wizard
  end	

end

app/helpers/booking_steps_helper.rb
module BookingStepsHelper

  def get_booking_friend_object_helper
    object = params[:friend_id].present? ? Friend.find(params[:friend_id]) : @booking.build_friend
  end


end

app/views/booking_steps/_form.html.haml
- if f.object.new_record?

  .form-group
    = f.label :fullname, 'Full name'
    = f.text_field :fullname, autofocus: true, class: 'form-control'

  .form-group
    = f.label :email, 'Email'
    = f.text_field :email, autofocus: true, class: 'form-control'


- unless f.object.gender.present?

  .form-group
    = f.label :gender, 'Gender', class: 'control-label'
    .radio
      %label
        = f.radio_button :gender, 'male'
        Male
    .radio
      %label
        = f.radio_button :gender, 'female'
        Female
        

.form-group
  = f.hidden_field :user_id, value: current_patient.id

- unless f.object.birthday.present?

  .form-group
    = f.label :birthday, 'Date of Birth'
    %br
    = f.date_select :birthday, {order: [:month, :day, :year], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, start_year: Date.today.year - 18, end_year: Date.today.year - 100}, {required: true, class: 'col-md-3 mr-50'}
    .clearfix

app/views/booking_steps/_friends_modal.html.haml
#myModal.modal.fade{:role => "dialog"}
  .modal-dialog
    / Modal content
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title Friends
      .modal-body
        %h4 Select one of your friend for treatment.

        - current_patient.friends.order('updated_at desc').each do |friend|
          
          - if is_friend_profile_incomplete?(friend)
            = link_to booking_step_path(:second, refer:true, friend_id: friend.id, booking_id: @booking.id) do
              .col-md-4
                .panel.panel-default
                  .panel-heading.preview
                    = image_tag('missing-patient.jpg')
                  .panel-body.text-center
                    %strong= friend.fullname.capitalize

          - else
            .col-md-4
              = form_for @booking, method: :put do |booking|
                = booking.hidden_field :status, value: true
                = booking.hidden_field :friend_id, value: friend.id
              
                .panel.panel-default
                  .panel-heading.preview
                    = image_tag('missing-patient.jpg')
                  .panel-body.text-center
                    %strong= friend.fullname.capitalize


      .clearfix
      .modal-footer
        %button.btn.btn-danger{"data-dismiss" => "modal", :type => "button"} Close

app/views/booking_steps/first.html.haml
.container

  .my-50
    .row
      .col-md-12
        .panel.panel-default
          .panel-heading
            Step1: Appointment for whom?
          .panel-body.box.text-center
            %h3.mb-20 Is this for you or someone else?

            - if is_user_profile_incomplete?
              = link_to booking_step_path(:second, booking_id: @booking.id) do
                .col-md-4
                  = image_tag('missing-patient.jpg')
                  %h4
                    %strong You

            - else
              .col-md-4
                = form_for @booking, method: :put do |booking|
                  = image_tag('missing-patient.jpg')
                  %h4
                    %strong You
                  = hidden_field_tag 'booking[status]', true



            - if current_patient.friends.present?        
              = link_to "javascript:void(0)", "data-target" => "#myModal", "data-toggle" => "modal" do
                .col-md-4
                  = image_tag('default-friend.jpg', class: 'img-circle')
                  %h4
                    %strong Your friend
              = render "friends_modal"



            = link_to booking_step_path(:second, refer:true, booking_id: @booking.id) do
              .col-md-4
                = image_tag('plus-in-circle.png')
                %h4 
                  %strong Someone else

- content_for :javascript do
  :javascript
    $('form.edit_booking').click(function(){
    $(this).submit();
    });

app/views/booking_steps/second.html.haml
.container
  .my-50
    .row
      = form_for @booking, method: :put do |booking|

        = booking.hidden_field :status, value: true

        - if params[:refer].eql?('true')

          .panel.panel-default
            .panel-heading
              Step2: Patient's details
            .panel-body.box
              = booking.fields_for :friend, get_booking_friend_object_helper do |friend|
                = render "form", f:  friend

        - else
          .panel.panel-default
            .panel-heading
              Step2: Need more details
            .panel-body.box
              = booking.fields_for :user, current_patient do |patient|
                
                = render "form", f:  patient              
                   

        
        .actions
          = booking.submit "Book appointment", class: 'btn btn-primary'      