config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)  


  devise_for :users,
             :path => '', :path_names => {:sign_in => 'sign-in', :sign_out => 'sign-out', :sign_up => 'sign-up',
             :edit_profile => 'profile'},
              :controllers => {:omniauth_callbacks => 'omniauth_callbacks', :registrations => 'registrations'}

  resources :users, only: [:show]
  resources :doctors, only: [:show]
  resources :patients, only: [:show]
  resources :rooms
  resources :photos

  resources :rooms do
    resources :reservations, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :rooms do
    resources :reviews, only: [:create, :destroy]
  end

  resources :rooms do
    resources :purchases, only: [:create]
  end
  resources :invites
  
  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  get '/your-trips' => 'reservations#your_trips'
  get '/your-reservations' => 'reservations#your_reservations'

  get '/your-sales' => 'purchases#your_sales'
  get '/your-purchases' => 'purchases#your_purchases'

  post '/notify' => 'reservations#notify'
  post '/your-trips' => 'reservations#your_trips'

  post '/purchase_notify' => 'purchases#notify'
  #post '/your-sales' => 'purchases#your_sales'

  get '/search' => 'pages#search'
  get '/dashboard' => 'pages#dashboard'
  

  resources :activities, only: [:index]
  resources :room_steps, only: [:show, :create, :update, :index]
  
  get '/family-members' => 'users#family_members'

  get 'users/:id/friends' => 'users#friends' , as: :friends
  get 'patient/:id/relatives' => 'patients#relatives'
  get 'patient/:id/bookings' => 'patients#bookings'
  
  get 'doctor/:id/leads' => 'doctors#leads', as: :leads 
  
  delete 'relative/:id' => "users#remove_relative"
  delete 'friend/:id' => "users#remove_friend"
  delete 'booking/:id' => "users#remove_booking"

  resources :bookings, only: [:create,:index, :update]
  get '/rooms/:room_id/booking' => "bookings#step_first"
  get '/sample' => "pages#sample"
  get '/test' => "pages#test"
  resources :booking_steps
  resources :categories, only: [:show]

  get '/mark_as_read' => "activities#mark_as_read"
   
end

app/models/room.rb
class Room < ActiveRecord::Base

  include PublicActivity::Common
  geocoded_by :address

  belongs_to :user
  has_many :photos, :dependent => :destroy
  has_many :reservations, :dependent => :destroy
  has_many :reviews, :dependent => :destroy
  has_many :purchases, :dependent => :destroy
  has_many :specialities, :dependent => :destroy
  has_many :educations, :dependent => :destroy
  has_many :breakthroughs, :dependent => :destroy
  has_many :awards, :dependent => :destroy  
  has_many :bookings, :dependent => :destroy

  has_many :rooms_conditions
  has_many :conditions, through: :rooms_conditions

  has_many :rooms_procedures
  has_many :procedures, through: :rooms_procedures

  has_many :rooms_insurances
  has_many :insurances, through: :rooms_insurances

  has_many :rooms_languages
  has_many :languages, through: :rooms_languages    


  has_many :groups
  has_many :members, through: :groups, source: :user

  accepts_nested_attributes_for :conditions, :specialities, :procedures, :insurances, :languages, :educations,:breakthroughs, :awards, :photos, :allow_destroy => true

  validates :listing_name, presence: true, length: {maximum: 50}
  validates :address, presence: true


  after_update :send_notification_after_activated
  after_create :send_notification_after_create
  after_validation :geocode
  
  scope :upgraded, -> { joins(:purchases).where('purchases.purchased_at >= ?', DateTime.now.to_date-30) }
  
  ## TODO it should be true
  scope :enabled, -> { where(is_admin_active: false) }

  def average_rating
    reviews.count == 0 ? 0 : reviews.average(:star).round(2)
  end

  def is_upgraded?
    if purchases.present? 
      last_upgrade = purchases.last
      last_upgrade.purchased_at.present? && ( DateTime.now.to_date - last_upgrade.purchased_at.to_date).to_i < 31
    end
  end
  
  private

  def send_notification_after_activated
    self.create_activity :update, owner: self.user, recipient: self.user if (self.is_admin_active_changed? && self.is_admin_active == true)
  end

  def send_notification_after_create
    self.create_activity :create, owner: self.user , recipient: self.user
  end


end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :set_room, only: [:show, :edit, :update]
  before_action :resources, only: [:show]
  before_action :create_instance, only: [:edit]

  skip_before_action :authenticate_patient!, :authenticate_doctor!

  def index
    @rooms = current_user.rooms.enabled.paginate(:page => params[:page], :per_page => 5)
  end

  def show;end

  def new
    @room = current_user.rooms.build
    @room.conditions.build
    @room.procedures.build
    @room.insurances.build
    @room.languages.build
    @room.educations.build
    @room.breakthroughs.build
    @room.awards.build
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      if params[:images]
        params[:images].each do |image|
          @room.photos.create(image: image)
        end
      end
      @photos = @room.photos
      @room.create_activity :create, owner: current_user, recipient: current_user
      redirect_to edit_room_path(@room), notice: "Saved!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @room.update_attributes(room_params)
      redirect_to room_path(@room), notice: "Your room has been successfully updated."
    else
      @errors = @room.errors
      render :edit
    end
  end

  private
    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(
        :listing_name, :zipcode, :street, :city, :state, :country, :price, :active, :degree, :biography, :category, :practice, :gender,:address,
        :conditions_attributes => [:condition,:_destroy,:id],
        :procedures_attributes => [:procedure,:_destroy,:id],
        :insurances_attributes => [:insurance_provider,:_destroy,:id],
        :languages_attributes => [:language,:_destroy,:id],
        :educations_attributes => [:school, :date,:_destroy,:id ],
        :breakthroughs_attributes => [:name, :date,:_destroy,:id ],
        :awards_attributes => [:name, :date,:_destroy,:id ],
        :condition_ids=>[],
        :language_ids=>[],
        :insurance_ids=>[],
        :procedure_ids=>[],
        :photos_attributes => [:image]
         )
    end

    def create_instance
      @room.conditions.build
      @room.procedures.build
      @room.insurances.build
      @room.languages.build
      @room.educations.build
      @room.breakthroughs.build
      @room.awards.build
    end

    def resources
      @photos = @room.photos
      @reviews = @room.reviews
      @bookings = @room.bookings
    end


end

app/helpers/rooms_helper.rb
module RoomsHelper

  def get_education_object_helper
    object = params[:education_id].present? ? Education.find(params[:education_id]) : @room.educations.build
  end  
end

app/views/rooms/_bookings.html.haml
.row              
  %h4 Leads (#{@bookings.length}) 
  - @bookings.first(3).each do |booking|
    - user = booking.user
    .col-md-4
      = link_to user_path(user) do
        .panel.panel-default
          .panel-heading.preview
            = image_tag avatar_url(user)
          .panel-body.text-center
            %strong= user.fullname.try(:capitalize)
  .clearfix        
  %strong= link_to "View more", "javascript:void(0)", class: 'pull-right'  if @bookings.length > 3

app/views/rooms/_card.html.haml
.panel.panel-default.docprofile.box
  = render "rooms/ribbon"

  .panel-defaultpanel-body

    .row

      .col-md-12
        .col-md-8.nopadding

          .col-md-3
            .image-cropper
              = image_tag @photos[0].try(:image) ? @photos[0].image.url(:medium) : "/assets/missing-room.jpg", class: 'img-responsive rounded'

          .col-md-9
            %h3
              = link_to room_path(@room) do 
                = @room.name 
                , #{@room.degree}, #{@room.category}
              
              - if @owner
                %a{href: edit_room_path(personal: true) }
                  %button.btn-circle.btn.btn-primary{:type => "button"}
                    %i.glyphicon.glyphicon-edit  

            - if @room.price.present?
              %span.btn.btn-info.btn-xs
                Rate  
                $
                = @room.price

            %span.small
              Address:
              = @room.address
            %h5
              Practice: #{@room.practice}
            
            %p
              = truncate(@room.biography,length: 30)
              = link_to "Read more", "javascript:void(0)", class: 'small'

            %h4
              Reviews
              %span#average_rating
              (#{@reviews.count})

        .col-md-4
          - if !user_signed_in? || current_patient
            = link_to 'Book An Appointment', booking_steps_path(room_id: @room.id), class: 'btn btn-block btn-primary'
          = render 'purchases/form_enterprise' if @owner && !@upgraded


- content_for :javascript do 
  :javascript
    $('#average_rating').raty ({
    readOnly: true,
    score: #{@room.average_rating}
    });

app/views/rooms/_edit_conditions.html.haml
= form_for(@room, url: room_path, method: :put) do |room|                  
  .form-group
    = room.select :condition_ids, Condition.all.map{|condition| [condition.name,condition.id] }, {}, {:multiple => true, class: 'chosen-select'}

  .pull-right
    = room.submit "Save" , class: "btn btn-primary btn-sm"

app/views/rooms/_edit_insurances.html.haml
= form_for(@room, url: room_path, method: :put) do |room|                  
  .form-group 
    = room.select :insurance_ids, Insurance.all.map{|insurance_provider| [insurance_provider.name,insurance_provider.id] }, {}, {:multiple => true, class: 'chosen-select'}

  .pull-right
    = room.submit "Save" , class: "btn btn-primary btn-sm"

app/views/rooms/_edit_languages.html.haml
= form_for(@room, url: room_path, method: :put) do |room|                  
  .form-group 
    = room.select :language_ids, Language.all.map{|language| [language.name, language.id] }, {}, {:multiple => true, class: 'chosen-select'}
  .pull-right
    = room.submit "Save" , class: "btn btn-primary btn-sm"

app/views/rooms/_edit_procedures.html.haml
= form_for(@room, url: room_path, method: :put) do |room|                  
  .form-group 
    = room.select :procedure_ids, Procedure.all.map{|procedure| [procedure.name,procedure.id] }, {}, {:multiple => true, class: 'chosen-select'}

  .pull-right
    = room.submit "Save" , class: "btn btn-primary btn-sm"

app/views/rooms/_photos.html.haml
.panel.panel-default
  .panel-heading
    Photos(#{@photos.size})
    / - if @owner
    /   %a{href: edit_room_path(photo: true) }
    /     %button.btn-circle.btn.btn-primary{:type => "button"}
    /       %i.glyphicon.glyphicon-plus 

  .panel-body.box
    / Carousel
    .mb-20
      - if @photos.present?
        .row
          .col-md-10.col-md-offset-1
            #myCarousel.carousel.slide{"data-ride" => "carousel"}
              / Indicators
              %ol.carousel-indicators
                - @photos.each do |photo|
                  %li{"data-slide-to" => "#{photo.id}", "data-target" => "#myCarousel"}
              / Wrapper for slides
              .carousel-inner{:role => "listbox"}
                - if @photos
                  - @photos.each do |photo|
                    %div{:class => "item #{'active' if photo.id == @photos[0].id}"}
                      = image_tag photo.image.url() 
              / Left and right controls
              %a.left.carousel-control{"data-slide" => "prev", :href => "#myCarousel", :role => "button"}
                %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
                %span.sr-only Previous
              %a.right.carousel-control{"data-slide" => "next", :href => "#myCarousel", :role => "button"}
                %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
                %span.sr-only Next

app/views/rooms/_ribbon.html.haml
- if @upgraded
  .ribbon
    %span Featured
-# elsif current_patient && user_booking.present?
  -#.ribbon
    -#%span Booked

app/views/rooms/_sidebarnav.html.haml
-# if current_user.rooms.where(:active => 't').empty?

- if true

  .col-md-3
    %ul.sidebar-list
      %li.sidebar-item
        %h4 Rooms
      =# link_to 'Rooms', rooms_path, class: active_class(rooms_path)
      / %li.sidebar-item= link_to 'Your Reservations', "javascript:void(0)", class: active_class(your_reservations_path)
      / %li.sidebar-item= link_to 'Your Trips', "javascript:void(0)", class: active_class(your_trips_path)
      / %li.sidebar-item= link_to 'Your Sales', "javascript:void(0)", class: active_class(your_sales_path)
      / %li.sidebar-item= link_to 'Family Members', "javascript:void(0)", class: active_class(your_sales_path)
      / %li.sidebar-item= link_to 'Friends', "javascript:void(0)" , class: active_class(your_sales_path)

/ - if false
/   .col-md-3
/     %ul.sidebar-list
/       %li.sidebar-item= link_to 'Dashboard', dashboard_path, class: active_class(dashboard_path)
/       %li.sidebar-item= link_to 'Leads', your_reservations_path, class: active_class(your_reservations_path)
/       %li.sidebar-item= link_to 'Reviews', your_reservations_path, class: active_class(your_reservations_path)
/       %li.sidebar-item= link_to 'Purchase History', your_purchases_path, class: active_class(your_purchases_path)
/       %br
/       %li.sidebar-item= link_to 'Add-ons', your_purchases_path, class: active_class(your_purchases_path)
/       %br
/       %li.btn.btn-primary.btn-block= link_to 'Upgrade Listing', your_trips_path, class: active_class(your_trips_path)
/       %br
/       %li.btn.btn-default.btn-block= link_to 'View My Listings', rooms_path, class: active_class(rooms_path)
/       %br

app/views/rooms/edit.html.haml
.container
  .my-50
    .row
      .col-md-3
        %ul.sidebar-list
          %li
            %strong Setting
        %br
        = link_to 'View profile', room_path(@room), class: 'btn btn-primary wide'

      .col-md-9
        = form_for(@room, html: { multipart: true } ) do |room|

          - if params[:personal].eql?("true")
            = hidden_field_tag :personal, true
            .panel.panel-default
              .panel-heading Update room profile
              .panel-body
                .form-group
                  
                  %label Upload your profile picture
                  = room.fields_for :photos, @room.photos.build do |photo|
                    = photo.file_field :image, onchange: 'readURL(this)'

                  =# room.file_field 'images[]', type: :file, multiple: true, onchange: 'readURL(this)'

                .form-group
                  = room.text_field :practice, placeholder: 'Enter the name of your practice', class: 'form-control'                    
                .form-group
                  = room.text_field :listing_name, placeholder: 'Enter your full name', class: 'form-control'
                .form-group
                  = room.text_area :biography, cols:10, rows:10, class: 'form-control', placeholder: 'Describe about yourself'
                .form-group
                  = room.select :gender, [['Male','Male'],['Female','Female']], include_blank: 'Select gender', class: 'form-control'
                .form-group
                  = room.text_field :address, placeholder: 'Enter a location', class: 'form-control'
                .form-group
                  -#%i.fa.fa-dollar
                  = room.text_field :price, placeholder: 'Consultation fees', class: 'form-control'                  
                .form-group
                  = room.select :degree, Degree.all.map{|degree| [degree.name, degree.name]}, include_blank: 'Select your professional degree', placeholder: 'Select your professional degree'
                .form-group
                  = room.select :category, Category.all.map{|category| [category.name, category.name]}, placeholder: 'I am an experienced', include_blank: 'I am an experienced'


          - if params[:education].eql?("true")
            = hidden_field_tag :education, true

            %label Add a education:
            
            = room.fields_for :educations, get_education_object_helper do |education|

              .form-group
                = education.text_field :school, placeholder: 'Enter the name of the school', class: 'form-control'
              .form-group                
                = education.date_select :date, {order: [:year], prompt: {year: 'Select year' }, start_year: Date.today.year - 18, end_year: Date.today.year - 100}, {required: false, class: 'col-md-3 mr-50'}
                .clearfix

              - unless education.object.new_record?                 
                = education.check_box :_destroy
                = education.label :_destroy, "Remove" , class: 'remove' 

          - if params[:condition].eql?("true")
            = hidden_field_tag :condition, true
            %label Conditons I'm experienced treating:
            
            = room.fields_for :conditions do |condition|
              .form-group
                = condition.select :condition, Symptom.all.map{|symptom| [symptom.name, symptom.name]} , prompt: "Select Conditions..", class: 'form-control'
              - unless condition.object.new_record?                 
                = condition.check_box :_destroy
                = condition.label :_destroy, "Remove" , class: 'remove' 


          - if params[:procedure].eql?("true")
            = hidden_field_tag :procedure, true

            %label Procedures I currently offer in my practice:
            
            = room.fields_for :procedures do |procedure|
              .form-group
                = procedure.select :procedure, Procedure::TYPES , prompt: "Select Procedures..", class: 'form-control'

              - unless procedure.object.new_record?                 
                = procedure.check_box :_destroy
                = procedure.label :_destroy, "Remove" , class: 'remove'           

          
          - if params[:insurance].eql?("true")
            = hidden_field_tag :insurance, true
            %label Insurance plans I currently accept in my practice:          
            
            = room.fields_for :insurances do |insurance|
              .form-group
                = insurance.select :insurance_provider, InsuranceProvider.all.map{|insurance_provider| [insurance_provider.name, insurance_provider.name]} , prompt: "Select Insurances..", class: 'form-control'
              - unless insurance.object.new_record?                 
                = insurance.check_box :_destroy
                = insurance.label :_destroy, "Remove" , class: 'remove'           

          - if params[:language].eql?("true")  
            = hidden_field_tag :language, true              
            %label Languages I speak:
            
            = room.fields_for :languages do |language|
              .form-group
                = language.select :language, Language::TYPES , prompt: "Select Conditions..", class: 'form-control'
              - unless language.object.new_record?                 
                = language.check_box :_destroy
                = language.label :_destroy, "Remove" , class: 'remove'           

          .actions
            = room.submit "Update", class: 'btn btn-primary'

app/views/rooms/index.html.haml
- count = @rooms.count

.container

  .my-50

  .row
    =# render 'sidebarnav'

    .col-md-12
      .panel.panel-default
        .panel-heading
          My Rooms
        .panel-body.box
          - if count > 0
            - @rooms.order('updated_at desc').each do |room|
              = link_to room_path(room) do
                .row.box
                  - if room.is_upgraded?
                    .ribbon
                      %span Featured
                  .col-md-2
                    - photos = room.photos
                    = image_tag photos[0].try(:image) ? photos[0].image.url(:medium) : "/assets/missing-room.jpg", class: 'img-responsive rounded'                  
                  .col-md-6
                    %h4
                      = room.practice
                      %a{href: edit_room_path(room, personal:true) }
                        %button.btn-circle.btn.btn-primary{:type => "button"}
                          %i.glyphicon.glyphicon-edit                   
                    %p= room.address
                  .col-md-4.right
                    - @room = room
                    = render 'purchases/form_enterprise' unless room.is_upgraded?
              %hr
            
            .pull-right= will_paginate @rooms

          - else
            .see-all-link 
              There is no enabled rooms yet.
              %a{href: '/room_steps'} List your practice      

app/views/rooms/show.html.haml
- @owner = (current_user == @room.user) ? true : false

- @upgraded = (@room.is_upgraded?) ? true : false

.container
  .my-50

    = render "card"
    = render "profile"
    = render "photos"  
    = render "near_by"

    .panel.panel-default
      .panel-heading
        %i.fa.fa-map-marker{"aria-hidden" => "true"}
        = @room.address
      .panel-body.box
        #google_map{style: "height:600px;"}

  
- content_for :javascript do 
  :javascript
    showMap();
    function showMap() {
    var mapDiv = document.getElementById('google_map');
    var map = new google.maps.Map(mapDiv, {center: {lat: #{ @room.latitude }, lng: #{ @room.longitude }},zoom: 15});
    var marker = new google.maps.Marker({position: {lat: #{ @room.latitude }, lng: #{ @room.longitude }}, title: "#{ @room.practice }" });
    marker.setMap(map);

    }

app/views/rooms/update.html.haml
%h1 Rooms#update
%p Find me in app/views/rooms/update.html.erb